### ISSUE TITLE
check-box Punktevergabe

### ISSUE THREAD

**Issue by Hanna303030** [bihor/fp_masterquiz#10]
Hallo,
folgendes Problem ist bei unserem Quiz aufgetaucht: Wenn ich bei richtigen Antworten eine 1 und bei falschen eine 0 eingebe, kann der Teilnehmer alle Antworten ankreuzen und bekommt dafür die volle Punktzahl. Wenn ich eine 1 für richtige Antworten eingebe und -1 für falsche Antworten, errechnet das Programm eine falsche "Gesamtpunktzahl" am Ende jeder Frage und auch eine falsche Gesamtpunktzahl für das Quiz insgesamt.

**Comment by bihor** [comment]
OK, dann muss ich da noch mal dran.

**Comment by Hanna303030** [comment]
Das wäre super!!! 👍

**Comment by bihor** [comment]
OK, ist nun in Version 1.1.2 gefixt.
