### ISSUE TITLE
Gesamtpunktzahl 

### ISSUE THREAD

**Issue by Hanna303030** [bihor/fp_masterquiz#11]
Kombination aus radio-button und check-box- Antworten verursacht Fehler in der Gesamtpunktzahl.
![Master-Quiz Gesamtpunktzahl](https://user-images.githubusercontent.com/70745270/98352217-029ec780-201e-11eb-96e3-63bf0ac45ced.png)

**Comment by bihor** [comment]
Ich dachte zuerst, die 4 soll hier falsch sein, aber ich nehme nun stark an, die 9 ist falsch.
Den Bug habe ich nun in Version 1.3.2 gefixt.
Bitte überprüfen.

**Comment by Hanna303030** [comment]
Funktioniert! Vielen, vielen Dank!

**Comment by Hanna303030** [comment]
Könnten Sie die neue Version noch auf die offizielle Download-Seite stellen? Das wäre super!
