### ISSUE TITLE
maximal points do not respect that only one answer can be choosen

### ISSUE THREAD

**Issue by linawolf** [bihor/fp_masterquiz#12]
I am using fp_masterquiz 1.4.2 on TYPO3 9.5.23

I have one quiz with two questions. in each question only one answer can be chosen. (select-box) the answers have 0, 1 or 2 points.

The quiz totals the reachable number of points to 6 where I would expect it to be 4.

https://github.com/bihor/fp_masterquiz/issues/11 suggests the issue got fixed with 1.3.2 however I am already using 1.4.2

**Comment by linawolf** [comment]
Attached Patch fixes the bug for me.

[[BUGFIX]_maximal_points_should_respect_that_only_one_answer_can_be_choosen.zip](https://github.com/bihor/fp_masterquiz/files/5607615/BUGFIX._maximal_points_should_respect_that_only_one_answer_can_be_choosen.zip)

**Comment by bihor** [comment]
OK, I have fixed this bug in version 1.4.4.

**Comment by linawolf** [comment]
Could you make 1.4.4 available via  packagist please?
