### ISSUE TITLE
Missing default value leads to SQL Error on saving

### ISSUE THREAD

**Issue by linawolf** [bihor/fp_masterquiz#13]
I am running fp_masterquiz 1.4.4 on TYPO3 9.5.23 and ddev with MariaDB 10.2

On creating tx_fpmasterquiz_domain_model_evaluation reccord I get the following error:
2: SQL error: 'Incorrect integer value: '' for column `db`.`tx_fpmasterquiz_domain_model_evaluation`.`page` at row 1' (tx_fpmasterquiz_domain_model_evaluation:NEW5fc5078b8190a939405297)

Attached Patch solves the issue for me by setting 0 as default value via TCA
[Bugfix_Missing_Defaults.zip](https://github.com/bihor/fp_masterquiz/files/5617310/Bugfix_Missing_Defaults.zip)

**Comment by bihor** [comment]
Fixed in version 1.4.5
