### ISSUE TITLE
Feature Request: Text and Image can be input directly in evaluation

### ISSUE THREAD

**Issue by linawolf** [bihor/fp_masterquiz#14]
For my editors it would be easier to input the text and image for an evaluation directly in the table tx_fpmasterquiz_domain_model_evaluation then to create a page or content element for each (we have a fixed scheme with one image and one text for each result but many tests).

Attached you find my proposal as feature request to include text and image directly in the table.
[Add_text_and_image_directly_to_table_evaluation.zip](https://github.com/bihor/fp_masterquiz/files/5622726/Add_text_and_image_directly_to_table_evaluation.zip)

**Comment by bihor** [comment]
I have made it with 2 varaibles in version 1.4.5.
