### ISSUE TITLE
Feature request: Make quiz categorizable

### ISSUE THREAD

**Issue by linawolf** [bihor/fp_masterquiz#15]
We do have a large number of quizzes that should belong to different categories. 

So I would like to suggest to make the quiz table categorizable.

Attached you find my solution for this: 

[make_quizzes_categorizable.zip](https://github.com/bihor/fp_masterquiz/files/5635566/make_quizzes_categorizable.zip) (updated to remove error in some contexts)

Greetings Lina

**Comment by linawolf** [comment]
[make_quizzes_categorizable.zip](https://github.com/bihor/fp_masterquiz/files/5641795/make_quizzes_categorizable.zip)

Just noted one file was missing in the patch, here is an update

**Comment by bihor** [comment]
Well, I cant see, for which purpose you have added Categories. Only in List.html is a usage.
I plan to use categories for selects too.

I think, this line is not needed: use \TYPO3\CMS\Extbase\Domain\Model\Category;
Instead I have added this line: $this->categories = new \TYPO3\CMS\Extbase\Persistence\ObjectStorage();

**Comment by linawolf** [comment]
Well we use custom templates in which we need categorizable quizes. For us depending on the category we are using different color-schemes, different headlines  like "Quiz your self on topic XY". 
I just included one example of how to output the categories in the extensions template as an example.

**Comment by linawolf** [comment]
for me it works fine like that, thank you
