### ISSUE TITLE
Feature add speaking urls

### ISSUE THREAD

**Issue by linawolf** [bihor/fp_masterquiz#16]
I would need a path_segment / slug to make speaking urls for quizzes. As others probably need them too, I would suggest to include a default routing configuration (as is done in the blog example) and a path_segment field (as is done in the news extension).

please find my patch attached. I also added some documentation in there.
[FEATURE_Add_speaking_urls.zip](https://github.com/bihor/fp_masterquiz/files/5652690/FEATURE_Add_speaking_urls.zip)

**Comment by bihor** [comment]
This is a good feature too.
I have added it.
