### ISSUE TITLE
question.allAnswers and answer.allPercent always 0

### ISSUE THREAD

**Issue by linawolf** [bihor/fp_masterquiz#18]
I would like to display how many percent of ppl answered a question with the same answer like me. 

By setting showAllAnswers I can get the absolute number of ppl who answered the same Answer like me in answer.allAnswers. There is also a variable called answer.allPercent, however that one is always 0. I suspekt this is due to the fact that question.allAnwers is also always 0.

**Comment by linawolf** [comment]
Attached you can find a patch which solves this issue for me. 
[[BUGFIX]_fix_allPercent_for_Answers_and_allAnswers_for_Question.zip](https://github.com/bihor/fp_masterquiz/files/5666330/BUGFIX._fix_allPercent_for_Answers_and_allAnswers_for_Question.zip)

**Comment by bihor** [comment]
OK, I have added it with this notation: setAllPercent(100 * ($total / $totalAnswers));
For me this is better readable.
Well, I had set setAllPercent only for the chart or result mode.
Can you add your template too so I can add allPercent to my template too?

**Comment by linawolf** [comment]
Trouble is, I am using Custom Templates that are very different from yours. On the final page of the Show Action I display a Balkendiagram of how many people choose what answer.

**Comment by bihor** [comment]
OK, I have added it to the Question/Result partial.

Have you more wishes? I am now ready for version 1.5.0.
