### ISSUE TITLE
Support for TYPO3 9.5

### ISSUE THREAD

**Issue by luwo1985** [bihor/fp_masterquiz#2]
Hi,

when I try to install the extension with composer I get an error message:

Problem 1
- The requested package fixpunkt/fp-masterquiz dev-* exists as fixpunkt/fp-masterquiz[dev-master, v0.5.1] but these are rejected by your constraint.

When I download the package 0.5.0 from TER as zip I saw that the composer.json file has the following entry:

"require" : {
		"typo3/cms-core" : "^8.7.1"
	},

Is it possible that there is still the old version ?

Thanks,
Lukas

**Comment by bihor** [comment]
OK, I have updated the composer-file.
I have tested it now and it works now.
