### ISSUE TITLE
Can't absolve a quiz

### ISSUE THREAD

**Issue by JeanJenkinz** [bihor/fp_masterquiz#20]
Hi bihor,

first of all: thank you for this extension!
I speak german better than english, but I'll try to explain my problem.

I downloaded, installed and configured the extension as explained in the docu.
I created a quiz in the folder and created a plugin on a page for the frontend.

But nothing happens when I answer the first question (checkbox) and hit the "continue"-button.
I tried it with multiple versions of my quiz and deactivated the other scripts on the site but nothing changed.

I get the following error in the DevTools: quiz.html:228 Uncaught ReferenceError: $ is not defined
For the following line: $( "#quiz-form"+ceuid+" .quiz-radiobox" ).click(function() {

I activated the debug too:
creating new session: 87695fe0bedc06c68
making new participant.
last page: 0; page: 1; reached page before: 0; next page: 1; showAnsers: 0
qs/qpp=2/1=2

Is that a issue or did I something wrong? I am grateful for every tip.

Thanks in advance and greetings from Germany! :)

Cheers,
Jean

**Comment by bihor** [comment]
Hallo Jean,
die Extension geht davon aus, dass jQuery im Header geladen wird, was bei dir anscheinend nicht der Fall ist.
Da gibt es 2 Möglichkeiten:
1. jQuery im Header statt im Footer laden
2. man muss ein if ins Show-Template hinzufügen:
```
window.onload = function () {
...
}
```

Und zwar um 

```
	<f:render partial="Quiz/CheckForm" arguments="{uidOfCE: uidOfCE}" />
	<f:render partial="Quiz/CheckFields" arguments="{uidOfCE: uidOfCE}" />
	
	$( "#quiz-GoOn" ).click(function() {
		// check if there are selected answers to all questions. if not, show an warning
		var allSelected = checkQuizForm();
		if (allSelected) {
			$('#quiz-form'+ceuid).submit();
		} else {
			window.alert(text_errorEmpty);
		}
	});

```

**Comment by JeanJenkinz** [comment]
Hallo Kurt,

vielen Dank für die schnelle Rückmeldung!
Es lag am JavaScript...entschuldige, mein Fehler. Danke vielmals für den Hinweis.

Ich wünsche frohe Weihnachten und einen guten Rutsch in ein gesundes neues Jahr!

Liebe Grüße,
Jean
