### ISSUE TITLE
Feature Images and other Media on quiz-level

### ISSUE THREAD

**Issue by linawolf** [bihor/fp_masterquiz#21]
I would need different images and or videos for a complete quiz.

In our case we use them in list view as they are required by our layout, 

But they could also be used on the quizpage itselft for layout or explainatory reasons.

Please see attached page
[[Feature]_Images_and_other_media_for_quizzes.zip](https://github.com/bihor/fp_masterquiz/files/5783220/Feature._Images_and_other_media_for_quizzes.zip)

**Comment by bihor** [comment]
There are 3 problems with this patch.
1. The new field is missing in ext_tables.sql
2. What about the fluid variable {file.type} ? It is not set! Did you set it in the controller?
3. And there is no switch-case for the video.

**Comment by bihor** [comment]
I guess, I will use {quiz.media.0.originalResource.type} instead of {file.type}
And I will use the f:media tag.

**Comment by linawolf** [comment]
sounds like a good idea. Didn't find time yet to improve my patch, sorry

**Comment by bihor** [comment]
OK, fixed.
