### ISSUE TITLE
Standard templates ignore  startPageUid

### ISSUE THREAD

**Issue by linawolf** [bihor/fp_masterquiz#22]
The list view ignores the starPageUid set in the flexform. I would suggest to add  pageUid="{settings.startPageUid}" to the viewhelper f.link.action.

**Comment by bihor** [comment]
I will check it when #21 is closed.

**Comment by bihor** [comment]
Well, startPageUid is reserved for this list-view.
I have added a new setting for the single-view: showPageUid.
Release-version 1.5.5.
