### ISSUE TITLE
Overview of text answers

### ISSUE THREAD

**Issue by msollmann** [bihor/fp_masterquiz#25]
Hi,

is there a backend overview of text answers? I would expect it in the chart, but there I can find only the number of text answers. In the list view of tx_fpmasterquiz_domain_model_selected records there is no possibility to show only text answers. So: where can I evaluate it?

Regards
Michael

**Comment by bihor** [comment]
I think this currently only at the "user details" visible.
You want to see all answers in the chart view?

**Comment by msollmann** [comment]
Yes, I would expect all answers in one place, so that I could export all results as a pdf.

**Comment by bihor** [comment]
OK, all answers of a text-question are now visible in the chart in the BE.
Version 2.1.3.

**Comment by msollmann** [comment]
Oh, great that you implemented it so quick!

I have tested it and found these issues:
- Not only textfield questions but also textarea questions should be displayed
- Because of the fixed height for every question there is not enough horizontal space for long answers in the chart
- Is there a possibility to scroll horizontal? I assume there is not enough space when having many answers. Could the answers be displayed as a simple textlist instead?
- As a "first answer" for every question the question itself is displayed (with 0x (0.00%)) in the chart. This is superfluous in my opinion.

Thanks!

**Comment by bihor** [comment]
OK:
- textarea now to
- text-answers are now under the chart
- the first answer is still there, because in a quiz it could be the correct answer

**Comment by bihor** [comment]
OK, I have added a margin and a ruler in version 2.1.9
