### ISSUE TITLE
Possibility to set user settings in plugin

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [bihor/fp_masterquiz#27]
Hi,

I installed your extension and like it so far! If I may suggest an improvement... user-settings should be editable in the plugin, especially useCookie and checkFEuser.

Use case: We use it mainly for (participation) surveys. Sometimes we allow users to vote multiple times and sometimes not. If so, a user could vote "yes" for a participation question and later on "no" because he's not able to show up for whatever reason.

Benefit: It's not practical if admins/integrators have to change it in typoscript with conditions, because a commit is necessary. The editor should be able to set it on its own without bugging us. :)

Sidenote: I know it clashes a bit when using it for surveys, because if a user votes multiple times, his former vote should not be considered in the result. Well, I think the best and most flexible solution would be if you could set in the plugin if a former vote (of the same fe-user or session user) gets "deleted" or not if a user votes again.

What do you think?

Cheers

**Comment by bihor** [comment]
OK, I will think about this feature.
More settings via FlexForm is a good idea.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Sounds promising, thanks. :)

**Comment by bihor** [comment]
OK, I have added some more FlexForms in version 3.0.10.
Sidenote: if the user-check is enabled, a user can not vote twice. Instead he will see his vote.
Therefore there is no need to delete an old vote...

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Wow, thank you for the effort! Will try it out soon, but it's not available on composer yet. ;)

**Comment by bihor** [comment]
OK, the release is now available.
