### ISSUE TITLE
Possibility to set questions as non mandatory

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [bihor/fp_masterquiz#28]
Hi.

in order to use it as a poll/survey, the possibility if a question is mandatory or not is missing. It seems that all questions are mandatory, which is of course not always wanted.

To be honest I overlooked this when evaluation poll extensions and didn't think this could be missing. ;) Any chance on implementing this in the future or did I miss something?

Cheers

**Comment by bihor** [comment]
Hi,
yes, your feature-wish is a good idea.
I will implement it.
Kurt

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Great, thank you!

**Comment by bihor** [comment]
Well, do you mean a check for every question?
Now, in version 3.0.9 you can disable the check for all questions with noFormCheck=1

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Hey... while noFormCheck is a good addition, I meant for every question. Some might be mandatory and some not, so a possibility for mixing it would cover all use cases.

Probably a lot of work?

**Comment by bihor** [comment]
In version 3.2.0 I have renamed mandatoryMark to optionalMark.
An option-text will be shown under the form if optionalMark is defined.
