### ISSUE TITLE
[QUESTION] How to avoid multiple votes if useCookie=1 but cookies are gone

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [bihor/fp_masterquiz#29]
Hi,

more a question than a request.  If useCookie=1 then a user cannot vote twice but it can be bypassed easily when the user

- ... deletes his cookies or the browser does it on restart (can be set in settings i think)
- ... changes his browser

Are there any additional (and reliable) checks one can do to identify a user and thus avoid multiple votes, even if one of the things above happened?

**Comment by bihor** [comment]
There would be only a second option to aviod multiple votes:
to block a user with the same IP address.
It could be possible to check the IP address.
Is that interesting?

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Hmm... I don't think an IP check is reliable enough. For example dynamic IP allocation or users sitting in the same company (with same IP) will distort the result.

A combination of cookie and IP could work though, but I'm not sure. Something like if cookie check is negative, compare the IP. But this should be optional.

Maybe there are best practice articles how to solve that the best way. :)

**Comment by DavidBruchmann** [comment]
Session?

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Ok, think so too. Thanks for your answers. I will close this now. :)
