### ISSUE TITLE
possible/reached points get messed up on page reload

### ISSUE THREAD

**Issue by HolgerHenning** [bihor/fp_masterquiz#3]
The possible/reached points get messed up when a page reload is triggered by the participant. 
On the first page of a quiz reloading the page results in the quiz beeing started all over. On the following pages the reload might resend the post data resulting in the points for the question(s) being counted multiple times.

**Comment by bihor** [comment]
OK, I have added a session-token to prevent reloads.
It works now for page 1.
So I need to do some more...

**Comment by bihor** [comment]
Would you like to test the version 0.5.4

**Comment by HolgerHenning** [comment]
Sorry for replying late. I gave it a (quick) test run. It's working pretty good so far. Thank you very much.
