### ISSUE TITLE
Answer is not considered if you redirect to the evaluation immediately

### ISSUE THREAD

**Issue by nollm** [bihor/fp_masterquiz#35]
**I've create a simple poll with a question and two answers.
In the content element I select only these three options so that the user comes to the evaluation immediately after answering the question.**

![settings_showAnswerPage](https://user-images.githubusercontent.com/42864489/163999751-10ac6347-ab04-415d-9228-9aee3d9f6d73.png)
![settings_showAnswersAtFinalPage](https://user-images.githubusercontent.com/42864489/163999770-d5640672-9ca8-4c92-a149-08b065a995b6.png)
![settings_showAllAnswers](https://user-images.githubusercontent.com/42864489/163999784-cc852122-e5c2-46f0-a05d-212f8f10ec5f.png)

**The problem is that the answer is not counted after I click on "go to the evaluation".**

![poll](https://user-images.githubusercontent.com/42864489/164000185-8f3b736a-f332-48d5-be9f-b628ed0893c5.png)
![evaluation_1](https://user-images.githubusercontent.com/42864489/164000194-86740669-9eab-4286-ac9b-5610bb4ad88d.png)

**If I start again, select "Answer 2" and click on "go to the evaluation" you can see that the previous answer is counted, but the current answer not.**

![evaluation_2](https://user-images.githubusercontent.com/42864489/164000495-56fba90c-96bc-4592-936e-fe5d42a81954.png)

**Can you confirm that this is a bug or have I configured something wrong?**

**Comment by bihor** [comment]
OK, I could confirm this problem.
Reason: the persist was done too late.
I moved the persist command and than it worked for me,
Please test it again with version 3.4.1.

**Comment by nollm** [comment]
Yes, that solves the problem.
Thank you very much for your fast response!
