### ISSUE TITLE
[Feature] Question-Matrix

### ISSUE THREAD

**Issue by akroii** [bihor/fp_masterquiz#43]
Is it possible  to implement a new question type?
Like this one:
![image](https://user-images.githubusercontent.com/8830861/195322399-4d997033-585b-4d2a-b3e1-3f2856924f71.png)

**Comment by bihor** [comment]
I think it would be necessary to add a new field to this table for this feature:
tx_fpmasterquiz_selected_answer_mm
I will think about that.

**Comment by akroii** [comment]
Did you wrapped your mind about that? 😀 Is there any update?

**Comment by bihor** [comment]
I will test if this is possible with categories of a queston.

**Comment by bihor** [comment]
OK, a first test worked.
The radio-options will come from the categories of a question.
The result will be saved as text in the entered-field.

**Comment by bihor** [comment]
I have added this feature in version 3.5.0. The options came from the categories of a question.
Example:
https://www.quizpalme.de/quiz-umfrage/umfragen/urlaubs-umfrage
No detailed results yet.
