### ISSUE TITLE
Cant solve a question / new participant

### ISSUE THREAD

**Issue by naturefund-falk** [bihor/fp_masterquiz#44]
Looks like i missed somewhere an important configuration step. Created a plugin on page, a quiz with 2 questions for now and an evaluation. After submitting the first result i get the following typo3 exception:
`
(1/1) #1249479819 TYPO3\CMS\Extbase\Persistence\Exception\UnknownObjectException

The object of type "Fixpunkt\FpMasterquiz\Domain\Model\Participant" given to update must be persisted already, but is new.
`
The participant form value is empty on submit and outputting the template variables for the page with the question shows, that the participant object is mostly empty and has no uid, ie its new (thats what the exception is showing).

I tried with setting useCookie -1 or 7 days, no difference.
What i am missing?

**Comment by bihor** [comment]
I have never seen this error.
Does it shows a line number?

**Comment by naturefund-falk** [comment]
Sorry, missed the email from github. This coud be such a fast response.

Ok, the line number itself is not realy helpful because its in the persistence manager. But i have the stack trace enabled on this development server:

- #0 /var/www/html/typo3/sysext/extbase/Classes/Persistence/Repository.php(117): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\PersistenceManager->update()
- #1 /var/www/html/typo3conf/ext/fp_masterquiz/Classes/Controller/QuizController.php(632): TYPO3\\CMS\\Extbase\\Persistence\\Repository->update()
- #2 /var/www/html/typo3conf/ext/fp_masterquiz/Classes/Controller/QuizController.php(1227): Fixpunkt\\FpMasterquiz\\Controller\\QuizController->doAll()
- #3 /var/www/html/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php(498): Fixpunkt\\FpMasterquiz\\Controller\\QuizController->showAction()
- removed other lines outside of your extension

**Comment by naturefund-falk** [comment]
My problem seems to come from the quizController->findParticipant function. It creates a NEW participant, but the later called doAll-function expects an already persisted participant ($this->participantRepository->update(...) only updates a persisted object, no NEW objects).
This seems to indicate that i miss the step where it creates a persisted participant.

**Comment by naturefund-falk** [comment]
Ok, i found the problem in our case. Its because we use in our typo3 installation a special persistence manager. The participantRepository is using it, but the invoked persistence manager in doAll is not. So the $participantRepository->add function is adding the new participant to the special persistence manager, while the later call to persistAll can not persist it, because it does not know about this object.

The explicit invocation of the PersistenceManager via objectmanager::get has to be replaced anyway, because in typo3 v12 this will be removed (the objectManager::get function, not the PersistenceManager). Maybe i manage to create a pull request for this.

**Comment by bihor** [comment]
OK, thanks for your hints.
I guess, you can fix it, so I wait for a solution from you.

**Comment by bihor** [comment]
Thanks for your pull request.
I think, this is fixed now in version 3.5.5.
