### ISSUE TITLE
[FEATURE] Close quiz/poll option in quiz/poll record

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [bihor/fp_masterquiz#47]
Hi Kurt :)

I'm back on track after a 6 months break. Still using your extension as a poll solution. Thanks for all the features you implemented lately (my own requests, matric mode etc.) and keeping it up with bug fixes.

We face a problem that fp_masterquiz cannot handle, so this is a feature request, maybe just an additional option request, I don't know.

Situation:  We have a poll where you only can participate once.

Request:  We want to be able to show the users own answers BUT no participation should be possible anymore. From what I see in the options, this is not possible. We can do the following:

1. Deactivate the plugin -> no user answers shown
2. Activate the plugin with show poll in switchableControllerActions -> user answers shown if you particpated but all other users can still participate (not wanted)

We cannot:

3. **Activate the plugin, show users answers but don't allow to participate (poll closed)**

Reason for the need: After a poll is closed, we get lots of questions from users who forgot what they answered. Example: "Did I say yes or no to the poll question?". This leads to questions which takes time to answer.

So what is missing is a "closed" checkbox in the poll record. If set to yes, only answers should be shown in the frontend (if show answers is set in switchableControllerActions). Ideally the closed-functionality is spiced with a from- and to-date, so you can prepare the poll duration beforehand instead of having to set it manually.

Possible messages in frontend:

"Poll will start soon." or "Poll will start on [DATE]" (selectable)
-> If show poll is selected in switchableControllerActions AND poll is not closed AND from-date is selected and not reached yet.

"Poll is closed, you cannot participate anymore."
-> If show poll is selected in switchableControllerActions AND (poll is closed OR to-date is reached).

Bonus: Option for correct wording (quiz or poll/survey) 

What do you think about it? :-)

**Comment by bihor** [comment]
Sorry for answering so late. I was very busy.

Well, your feature-request makes sense.
I think, I will implement it in January.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Wow, sounds good. Thank you! if you need help with testing, let me know.

**Comment by bihor** [comment]
Well, I didn´t wanted to make it complicated.
I just added the setting "closed", which can be set via FlexForms too.
Users you voted, will then see their result. Other users will get a message.
Furthermore I added a type select-box to quiz to improve the message from about.
Can you test that in version 3.5.8?

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Thanks. Will do so when I have a free spot!

**Comment by bihor** [comment]
Well, now I think a checkbox at the quiz-entry would be better than at the FlexForms.
I think, I will add that checkbox to a quiz too.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
With quiz entry you mean poll record? At least that's what I suggested in my initial post.

**Comment by bihor** [comment]
![closed](https://user-images.githubusercontent.com/8191408/224721383-aa3fc141-eb9a-4ded-8b7e-7fd2ce545246.jpg)

Poll entry or quiz entry.
I have added a checkox there too. You find it at the access-tab in version 3.6.1.
The setting will remain too.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Great, thank you! Will try it out ASAP and report back.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Great addition, we use it often! Sorry for not reporting back then, slipped through my fingers somehow.
