### ISSUE TITLE
Any plans for TYPO3 v12 Compability?

### ISSUE THREAD

**Issue by linawolf** [bihor/fp_masterquiz#50]

**Comment by linawolf** [comment]
Is there a branch?

**Comment by bihor** [comment]
Version for TYPO3 10 and 11 is in a new branch.
The current beta version fpr TYPO3 12 is in the master branch.
But it is not running yet.

**Comment by bihor** [comment]
I have now released the first beta version for TYPO3 12.
If you want, you can test it now.
But I think, the Ajax version is still not runing.

**Comment by linawolf** [comment]
Wonderful, I actually have a large project that I need to update to v12 right now. It is making extended usage of your quizzes. So I have real life test cases ;)

**Comment by bihor** [comment]
Done.
