### ISSUE TITLE
Redirect to results page

### ISSUE THREAD

**Issue by p380** [bihor/fp_masterquiz#54]
I have a question, is there a plugin setting where after completing the survey it automatically redirects to the page with the survey results

Regards

**Comment by bihor** [comment]
This was not possible. I added this feature to version 4.2.3:
https://github.com/bihor/fp_masterquiz/releases
Or do you need this feature for another TYPO3 version?

**Comment by p380** [comment]
we have it installed on v. typo3 11 
but we solved the issue in the fluid template in the form with the pageUid parameter

thanx

**Comment by bihor** [comment]
Ah, OK.
Do you use then 2 plugins on the result-page?
One for saving the data and one for displaying the results?
