### ISSUE TITLE
Points per correct answered question

### ISSUE THREAD

**Issue by gckng** [bihor/fp_masterquiz#55]
Hello!
Is there any possibility to create the following scenario?
We would like to credit the user with one point per question, if the question is answered correctly.
For single choice questions (radio) this is no problem at all. But we have got mixed quizzes with single and multiple choice questions.
A multiple choice question for example has 5 answers and 3 of them are true. The user should be awarded with one point for this question only if he chooses all 3 correct answers.
The evaluation should only count correct answered questions (e.g. 12 out of 20).

**Comment by bihor** [comment]
This is currently not possible, but I think it is a very good feature.
I will implement it in the next version.

**Comment by bihor** [comment]
OK, I have added in version 4.3.0 the setting pointsMode.
Try pointsMode=3
Is it OK?

**Comment by bihor** [comment]
Oh, I forget to set the given points to 1 instead of e.g. 1.
But now only correct answered questions are counted.

**Comment by bihor** [comment]
You can now try settings.pointsMode.4 with version 4.3.1
Is it OK?

**Comment by gckng** [comment]
Thank you very much! That looks great.

**Comment by bihor** [comment]
I think, this was not done correct:
- The evaluation should only count correct answered questions (e.g. 12 out of 20).

I fixed that in version 5.0.1.
