### ISSUE TITLE
Edit FinalPage.html

### ISSUE THREAD

**Issue by UM-Elizabeth** [bihor/fp_masterquiz#6]
Hi there! This quiz is perfect for our needs except we need the option to download a PDF certificate once the quiz is complete. Therefore we need to add extra content to the file FinalPage.html. Rather than editing your code (in case of updates) I would prefer to create new Partial HTML files but I cannot override the property plugin.tx_fpmasterquiz.view.partialRootPath except within your extension.

To clarify, my new templates are used when I edit your file: fp_masterquiz\Configuration\TypoScript\contants.ts
partialRootPath = EXT:my_extension/Resources/Private/Partials/MasterQuiz

But when I edit the extension in my code it still uses your templates:
my_extension\Configuration\TypoScript\Template\root.txt
plugin.tx_fpmasterquiz.view.partialRootPath = EXT:my_extension/Resources/Private/Partials/MasterQuiz

And I know that my configuration is OK because other settings over overridden OK E.g.
my_extension\Configuration\TypoScript\Template\root.txt
plugin.tx_fpmasterquiz.settings.user.checkFEuser = 1

I can see in your settings.yaml that 
overwriteSettings:
Resources:
    Private:
      Partials: keep

Is this the problem? Or is there something else I am missing.

Thanks
Elizabeth

**Comment by bihor** [comment]
I do not understand all.
You want to change the path to the templates?
Its better, you use the TypoScript-Setup instead of the Constants.
Use this:
plugin.tx_fpmasterquiz.view.partialRootPaths.1 = EXT:my_extension/Resources/Private/Partials/MasterQuiz

**Comment by bihor** [comment]
settings.yaml is only for the ExtensionBuilder.
You can ignore it.

**Comment by bihor** [comment]
If you are using the Ajax-Version: all settings must be done at the root level.
E.g. on page with id=1.

**Comment by UM-Elizabeth** [comment]
Hi there,

Thanks for your help. I can edit the file in your extension but editing it in my setup file doesn't work - not sure why. I've edited it in your files as a temporary measure.

Thanks,
Elizabeth
